# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About Us"
url = "about/"
weight = 2

#[[main]]
#name = "FAQ"
#url = "faq/"
#weight = 3


  
[[main]]
name = "Contact Us"
url = "contact/"
weight = 3


#[[main]]
#name = "Blogs"
#url = "blog/"
#weight = 5


# footer menu
[[footer]]
name = "About Us"
url = "about/"
weight = 1


[[footer]]
name = "Contact Us"
url = "contact/"
weight = 2

